name: blackhole
description: A beautiful music player for Android
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  on_audio_query: ^2.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  sqflite: ^2.3.0
  flutter_media_metadata: ^1.0.0+1
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1
  flutter_displaymode: ^0.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  flutter_animate: ^4.3.0
  flutter_lyrics: ^0.5.0
  flutter_media_metadata: ^1.0.0+1
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1
  flutter_displaymode: ^0.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  flutter_animate: ^4.3.0
  flutter_lyrics: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 